### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by masonlouchart** [RichardCzechowski/polymer-badge#1]
Hi, the readme file is not related to the element.

**Comment by RichardCzechowski** [comment]
Yes, thanks for catching that. I copied the core over from another component. Since this was my first polymer component, and I didn't expect anyone to be interested, I never revisited it. Mistake has been rectified.

**Comment by masonlouchart** [comment]
When I seen this repo I thought the component was aborted.  So I decided to create my own [poly-badge](https://github.com/LM450N/poly-badge). And guess what...it's also my first component ^^".

Maybe I should have worked with your. But I'm looking for a badge with few default features. Like have an info tag or warning tag just with one attribute. Sorry.

It looks I used an old generator so I'll remove my repo and create a new one.

**Comment by RichardCzechowski** [comment]
Yeah, I was just fooling around a while back. It is aborted, I just never delete old/unfinished repos, I probably should.
Your badge is great btw, I like that you made it so robust.
